# Use macOS with XCode 10
os: osx
osx_image: xcode10

# Use Node 10.x and yarn
language: node_js
node_js:
  - "10"
cache: yarn

install:
# Set up RVM, RubyGems, Bundler
  - rvm install 2.4.3
  - rvm use 2.4.3 --default
  - gem update --system
  - gem install bundler
  - bundle check || bundle install
# Install NPM deps
  - yarn

script:
  # Requires Android SDK
  # - bundle exec fastlane android test
  - bundle exec fastlane ios test
  - yarn lint
  # - yarn test
